/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.curso;

import edu.curso.view.CLIMedicamentoUI;

public class App {
    public static void main(String[] args) {
        CLIMedicamentoUI test = new CLIMedicamentoUI();
        test.iniciar();
    }
}
